/* Salisbury 1245: captions and the guided tour.
 *
 * Every caption with a fact card (body + source) uses facts the dossier marks verified,
 * with the URL it was verified from. Where the drawing reconstructs something (the wheel,
 * the staging of the nave, the yard), the caption says so.
 */

export function captions(k) {
  const L = (d) => k.label(d);
  // Overview captions.
  L({ x: 64, y: 47, z: 2, title: 'No spire yet!', text: 'The tower was heightened and the 123-metre spire added only between about 1300 and 1329.', min: 2, priority: 3, body: 'The crossing tower was raised and the 123-metre (404 ft) spire built only between about 1300 and 1329. Its form in 1245 is not recorded, so the low stage and temporary cap drawn here are a reconstruction.', source: 'https://www.salisburycathedral.org.uk/discover/history/the-cathedral-through-the-years/' });
  L({ x: 61.5, y: 12, z: 1, title: 'Church and building site in one', text: 'East of this screen canons sing the daily services; west of it the nave is still being built.', min: 2, priority: 3, body: 'Salisbury was built from east to west. The quire and eastern transept were complete by about 1236 and the church was in daily use while the nave went up in the 1240s. The whole church was consecrated in 1258. The boarded screen here is illustrative.', source: 'https://de.wikipedia.org/wiki/Kathedrale_von_Salisbury' });
  L({ x: 30, y: 15, z: 6, title: 'Ten bays, 84 feet high', text: 'The finished nave will be 229 feet long and 84 feet high, with walls of grey freestone and shafts of Purbeck marble.', min: 2, priority: 2, body: 'The 1911 Britannica gives the nave as 229 ft 6 in long and 84 ft high, in ten bays, built of grey freestone with shafts of Purbeck marble. The state of each bay in June 1245 is not recorded: the staircase of half-built bays drawn here is a reconstruction consistent with the dates.', source: 'https://en.wikisource.org/wiki/1911_Encyclop%C3%A6dia_Britannica/Salisbury' });
  L({ x: 132, y: 15, z: 4, title: 'The first part finished', text: 'By 1225 the east end had risen far enough for three altars to be consecrated.', min: 2, priority: 2, body: 'Building began at the east end. By 1225 it had risen far enough for three altars to be consecrated, with Archbishop Stephen Langton preaching; soon after, King Henry III and many great lords came to see the new work.', source: 'https://www.british-history.ac.uk/vch/wilts/vol3/pp156-183' });
  L({ x: 25, y: 62, z: 74, title: 'A tower of its own', text: 'North of the nave stood a massive detached belfry: three tiers and a spire, 200 feet in all.', min: 3.5, priority: 1, body: 'The Victoria County History describes the detached belfry about 200 ft north of the nave: walls 8 ft thick, three tiers and a spire, 200 ft high in all, erected in the earlier 13th century. Whether it was complete by 1245 is not known.', source: 'https://www.british-history.ac.uk/vch/wilts/vol6/pp72-79' });
  L({ x: 80, y: 78, z: 1050, title: 'Leaving the hill', text: 'The first cathedral stood inside a hilltop fortress two miles away, at Old Sarum.', min: 4, priority: 1, body: 'The clergy at Old Sarum complained of quarrels with the castle guards, a shortage of water and stormy weather. With royal approval, many stones for the new cathedral were taken from the old one.', source: 'https://www.salisburycathedral.org.uk/discover/history/the-cathedral-that-moved/' });
  L({ x: -24, y: 9, z: 3, title: 'The works yard', text: 'Lodge, tracing loft, smithy and bell pit west of the rising nave. Where they really stood is not recorded.', min: 2, priority: 2 });
  L({ x: 152, y: 7, z: 2, title: 'Masons\' quarter', text: 'Records place 13th-century masons living just east of the Close.', min: 3, priority: 1, body: 'The Victoria County History places 13th-century masons living just east of the Close, perhaps the cathedral workmen\'s own settlement. Master Nicholas of Ely, the resident master mason, was given a house plot in the new city about 1230. The cottages drawn here are illustrative.', source: 'https://www.british-history.ac.uk/vch/wilts/vol6/pp72-79' });

  // Room-level captions.
  L({ x: -17, y: 4.4, z: 2, title: 'Drawing at full size', text: 'Window and vault designs were scratched full size into a thin plaster floor.', min: 10, body: 'Designs for windows and vaults were scratched full size into a thin plaster floor; when it was full, a fresh layer went on. Such floors survive at York and Wells. Where Salisbury\'s stood is not recorded.', source: 'https://de.wikipedia.org/wiki/Rei%C3%9Fboden' });
  L({ x: -19.2, y: 1.6, z: 3, title: 'Sign your work', text: 'Masons paid by the piece cut a banker mark on each finished stone.', min: 10, body: 'Masons paid by the piece cut a personal banker mark on each finished stone so the paymaster knew who had made it.', source: 'https://en.wikipedia.org/wiki/Mason%27s_mark' });
  L({ x: -11.6, y: 1.3, z: 2.8, title: 'Marble that is not marble', text: 'Purbeck "marble" is a limestone packed with fossil freshwater snails.', min: 12, body: 'Purbeck marble is a limestone packed with fossil freshwater snails. It takes a fine polish, which is how it earned the name. Corfe had a large medieval marble-carving trade, and Purbeck stone was shipped all round the country from Ower Quay in Poole Harbour.', source: 'https://en.wikipedia.org/wiki/Purbeck_Marble' });
  L({ x: -9.4, y: 1.3, z: 2.8, title: 'Painting with glass', text: 'The glazier draws the window full size on a whitewashed table, cuts and grozes each piece, and paints details before firing.', min: 12, body: 'The glazier drew the window full size on a whitewashed table, cut each piece, nibbled its edges with a grozing iron and painted details in black glass paint before firing. Lead cames hold the pieces together.', source: 'https://en.wikipedia.org/wiki/Stained_glass' });
  L({ x: -25, y: 2.4, z: 2.5, title: 'Smithy', text: 'The smith keeps the masons\' chisels sharp and makes iron cramps and nails.', min: 10 });
  L({ x: -30.4, y: -1.0, z: 0.6, title: 'Bells cast on the spot', text: 'Bells were often cast in pits beside the church, mouth down between a clay core and an outer cope.', min: 9, body: 'Bells were often cast on site in pits in a church or its grounds, mouth down in a two-part mould, a core and a cope, shaped with strickle boards. Bell metal is about 78 percent copper and 22 percent tin. This pit\'s place in the yard is illustrative.', source: 'https://en.wikipedia.org/wiki/Bellfounding' });
  L({ x: -6.5, y: 2.0, z: 1.2, title: 'Paying for it', text: 'From 1219 every canon, vicar and chaplain gave a fixed share of his income to the building fund.', min: 10, body: 'From 1219 every canon, vicar and chaplain had to give a fixed share of his income to the building fund for seven years. When the vicars choral refused to go out collecting alms, seven senior clergy went instead, some as far as Scotland and Ireland.', source: 'https://www.british-history.ac.uk/vch/wilts/vol3/pp156-183' });
  L({ x: -2.8, y: 0.4, z: 1.0, title: 'Burning stone', text: 'Mortar is lime and sand. Lime is limestone heated to around 900 to 1000 degrees C, then slaked with water.', min: 10, body: 'Quicklime is made by heating limestone, usually to about 900 to 1000 degrees C, and becomes slaked lime when mixed with water. Lime mortar sets slowly in the air.', source: 'https://en.wikipedia.org/wiki/Lime_kiln' });
  L({ x: -1.3, y: 0.9, z: 6.9, title: 'Brand-new technology', text: 'The wheelbarrow\'s first European record is a 1222 purchase for the king\'s works at Dover.', min: 14, body: 'The wheelbarrow\'s first European record is a purchase of 1222 for the king\'s works at Dover.', source: 'https://en.wikipedia.org/wiki/Wheelbarrow' });
  L({ x: -36, y: 1.6, z: 3, title: 'Stone from the west', text: 'Chilmark stone was quarried about 11 miles west, and probably came by ox-cart.', min: 8, body: 'Chilmark stone was quarried about 11 miles west. It probably came by ox-cart, because weirs and watermills blocked boats on the River Nadder.', source: 'https://en.wikipedia.org/wiki/Salisbury' });
  L({ x: -43, y: 1.4, z: 2.5, title: 'Not only men', text: 'Women and children worked here too, carrying goods, tending animals and providing food.', min: 9, body: 'Both skilled and unskilled workers built the cathedral, and women and children helped by carrying goods, tending animals and providing food.', source: 'https://www.salisburycathedral.org.uk/discover/history/the-cathedral-that-moved/' });
  L({ x: 2.6, y: -0.6, z: 0, title: 'Shallow roots', text: 'The water table is so high that the cathedral stands on foundations only 1.2 metres deep.', min: 5, priority: 2, body: 'The water table is so high that the whole cathedral stands on foundations only 1.2 metres (4 feet) deep, with gravel and water beneath.', source: 'https://www.salisburycathedral.org.uk/discover/history/the-cathedral-that-moved/' });
  L({ x: 13.9, y: 0.8, z: 10.6, title: 'Recycling', text: 'With royal approval, many stones were taken from the old cathedral at Old Sarum.', min: 14, body: 'With royal approval, many stones for the new cathedral were taken from the old one at Old Sarum. The carved block drawn here is illustrative.', source: 'https://en.wikipedia.org/wiki/Salisbury' });
  L({ x: 25, y: 11.5, z: 6.4, title: 'Striking the centring', text: 'Each arch is built over a timber frame. When the keystone is in, the wedges are knocked out and the frame comes down.', min: 8, body: 'Each arch is built over a timber frame called centring. When the keystone is in, the centring is struck: its wedges are knocked out and the frame is lowered and removed.', source: 'https://en.wikipedia.org/wiki/Centring' });
  L({ x: 33, y: 7.4, z: 10.8, title: 'Holes for poles', text: 'Scaffold poles called putlogs rest in small holes left in the wall.', min: 9, body: 'Scaffold poles called putlogs rest in small holes left in the wall. The holes on the outside are filled when the scaffold comes down.', source: 'https://en.wikipedia.org/wiki/Putlog_hole' });
  L({ x: 57, y: 33.4, z: 2, title: 'Cranes climb with the building', text: 'Hoists started on the ground, then were rebuilt on the roof tie beams and moved from bay to bay.', min: 7, priority: 2, body: 'Medieval cranes were not perched on scaffolds. They started on the ground inside the building, then were dismantled and rebuilt on the roof tie beams and moved from bay to bay. They rarely had ratchets or brakes: the friction of the great wheel stopped a load from running back.', source: 'https://en.wikipedia.org/wiki/Treadwheel_crane' });
  L({ x: 56, y: 28.9, z: 0.6, title: 'A guess, honestly labelled', text: 'Treadwheels appear in France around 1225, but England\'s first written record of one is 1331. This wheel is a plausible reconstruction.', min: 12, body: 'The earliest treadwheel reference is from France about 1225, and in England the treadwheel is not recorded before 1331. Spoked and crank windlasses were also in use. This wheel is drawn as a plausible guess.', source: 'https://en.wikipedia.org/wiki/Treadwheel_crane' });
  L({ x: 60.2, y: 2.0, z: 2.1, title: 'Gripping a stone', text: 'A lewis in a shaped hole in the top of a block, or iron scissor-tongs, hold each stone as it is hoisted.', min: 14, body: 'A lewis, set in a shaped hole in the top of a block, or iron scissor-tongs gripping its sides, held each stone as it was hoisted. Medieval builders hung such external lewises from cranes.', source: 'https://en.wikipedia.org/wiki/Lewis_(lifting_appliance)' });
  L({ x: 48.5, y: 0.6, z: 1.0, title: 'Lead workers', text: '"Plumber" comes from plumbum, Latin for lead. Lead melts at only 327.5 degrees C.', min: 10, body: '"Plumber" comes from plumbum, Latin for lead: in the Middle Ages anyone who worked lead was a plumber. Lead melts at only 327.5 degrees C. The casting method drawn here is illustrative.', source: 'https://en.wikipedia.org/wiki/Plumber' });
  L({ x: 55, y: 34.5, z: 3, title: 'Royal oaks', text: 'King Henry III made many gifts of timber and money to the building.', min: 9, body: 'King Henry III made many gifts of timber and money to the building of the cathedral.', source: 'https://www.british-history.ac.uk/vch/wilts/vol3/pp156-183' });
  L({ x: 82, y: 3.0, z: 4.0, title: 'New stalls', text: 'The quire\'s oak stalls were made around 1236; under Bishop Bingham the quire was roofed with lead and glazed.', min: 8, priority: 1, body: 'The quire\'s oak stalls were made around 1236. Under Bishop Robert Bingham the quire was roofed with lead and glazed. The services sung here, the Use of Sarum, were later adopted by churches across southern England, Wales and parts of Ireland.', source: 'https://de.wikipedia.org/wiki/Kathedrale_von_Salisbury' });
  L({ x: 88, y: 15, z: 5.6, title: 'English, not French', text: 'Salisbury keeps a low middle storey, plain four-part rib vaults and simple bell-shaped capitals.', min: 8, body: 'Salisbury keeps a low middle storey, plain four-part rib vaults and simple bell-shaped capitals, hallmarks of Early English Gothic.', source: 'https://en.wikipedia.org/wiki/Early_English_Gothic' });
  L({ x: 110, y: 7.5, z: 11.7, title: 'Lancets, not tracery', text: 'Windows are tall pointed lancets: two to each aisle bay, stepped groups of three in the clerestory.', min: 9, body: 'Windows are tall pointed lancets, two to each aisle bay and stepped groups of three in the clerestory. A new 13th-century fashion was grisaille, abstract leaf patterns on greyish glass; yellow silver stain did not arrive until soon after 1300.', source: 'https://de.wikipedia.org/wiki/Kathedrale_von_Salisbury' });
  L({ x: 135, y: 4.5, z: 3.2, title: 'Daring shafts', text: 'Single Purbeck marble shafts, astonishingly slim, carry parts of the Trinity Chapel\'s vault.', min: 8, body: 'Single Purbeck marble shafts, astonishingly slim, carry parts of the Trinity Chapel\'s vault.', source: 'https://en.wikipedia.org/wiki/Early_English_Gothic' });
  L({ x: 126.9, y: 1.5, z: 9.1, title: 'First burial', text: 'William Longespee, half-brother of King John, died in March 1226 and was the first person buried in the new cathedral.', min: 12, body: 'William Longespee, Earl of Salisbury and half-brother of King John, died in March 1226 and was the first person buried in the new cathedral. He and Ela, Countess of Salisbury, had both laid foundation stones. The tombs drawn here are illustrative.', source: 'https://en.wikipedia.org/wiki/Salisbury_Cathedral' });
  L({ x: 82.5, y: 21.6, z: 2.0, title: 'A painted vault', text: 'These vaults were later painted with prophets, Christ in Majesty and the labours of the months. Whether painting had begun by 1245 is not known.', min: 12 });
}

export function tour(W) {
  W.stop({ x: 55, y: 18, z: 3, w: 230, hour: 10.5, title: 'Salisbury, midsummer 1245', text: 'A cathedral half built and half in use. The east end is finished, vaulted and roofed in lead, and the canons sing their services there. To the west the nave climbs bay by bay out of a busy works yard.', hold: 11 });
  W.stop({ x: -20, y: 3, z: 3, w: 46, hour: 9.2, title: 'The works yard', text: 'Stone arrives by ox-cart from Chilmark. Masons dress it at their bankers in the lodge, the warden draws full-size arcs on the tracing floor upstairs, the smith re-steels their chisels, and a bell-founder builds a mould in a pit.', hold: 11 });
  W.stop({ x: 30, y: 9, z: 5, w: 52, hour: 9.6, title: 'The nave rising', text: 'From west to east the bays climb like a staircase: pier bases, then arches on timber centring, then the clerestory going up on a tall scaffold. A windlass hauls stone to the aisle wall.', hold: 11 });
  W.stop({ x: 56, y: 30, z: 2, w: 24, hour: 13.2, title: 'Up on the tie beams', text: 'Carpenters peg the rafters, plumbers dress lead on the ridge, and two men walk a great wheel to lift stone from the floor 27 metres below. The wheel is a plausible guess: England\'s first record of a treadwheel is from 1331.', hold: 12 });
  W.stop({ x: 64, y: 8, z: 3, w: 34, hour: 10.2, title: 'Church and site in one', text: 'A boarded screen separates the building site from the church. On one side, mallets and the creak of the wheel; on the other, High Mass in the quire.', hold: 10 });
  W.stop({ x: 92, y: 7, z: 3, w: 40, hour: 10.0, title: 'High Mass in the quire', text: 'Canons and vicars choral sing in the oak stalls made about 1236, with the choirboys on the forms below. A thurible swings before the high altar.', hold: 11 });
  W.stop({ x: 132, y: 6, z: 3, w: 30, hour: 7.2, title: 'The Trinity Chapel', text: 'The oldest part of the church, where three altars were consecrated in 1225. Its vault stands on single shafts of Purbeck marble so slim they seem impossible.', hold: 10 });
  W.stop({ x: 84, y: 6, z: 3, w: 40, hour: 2.6, title: 'Matins by candlelight', text: 'In the small hours the clergy sing the night office in the candlelit quire, while the building site lies dark and the watchman makes his rounds.', hold: 12 });
  W.stop({ x: 152, y: 2.5, z: 2, w: 22, hour: 22.5, title: 'Home', text: 'In the cottages east of the Close the hearths glow and the masons\' families sleep. At first light the work begins again.', hold: 10 });
}
