#!/usr/bin/env node
/* Build the portable single-file edition: dist/cross-sections.html.
 *
 *   node tools/build.js          write dist/cross-sections.html
 *   node tools/build.js --check  exit 1 if the committed file is out of date
 *
 * esbuild bundles src/main.js (three.js, cannon-es and every scene) into one inline
 * module; the stylesheet and gallery thumbnails are inlined too. The result opens from
 * a file, a USB stick or a web server, with no network access.
 */
import { build } from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(root, 'dist', 'cross-sections.html');
const check = process.argv.includes('--check');

const res = await build({
  entryPoints: [path.join(root, 'src', 'main.js')],
  bundle: true,
  format: 'esm',
  target: 'es2020',
  minify: true,
  write: false,
  legalComments: 'eof',
  logLevel: 'warning',
  charset: 'utf8',
});
let js = res.outputFiles[0].text.replace(/<\/script/gi, '<\\/script');
const css = fs.readFileSync(path.join(root, 'src', 'styles', 'app.css'), 'utf8');

// Thumbnails for the contents page, if they have been rendered (tools/thumbs.cjs).
const thumbs = {};
const gdir = path.join(root, 'gallery');
if (fs.existsSync(gdir)) {
  for (const f of fs.readdirSync(gdir).sort()) {
    const m = f.match(/^([a-z0-9-]+)\.jpg$/);
    if (m) thumbs[m[1]] = 'data:image/jpeg;base64,' + fs.readFileSync(path.join(gdir, f)).toString('base64');
  }
}

let html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
html = html.replace(/<link rel="stylesheet" href="src\/styles\/app.css">/, () => '<style>\n' + css + '</style>');
const start = html.indexOf('<!-- Development entry');
const end = html.indexOf('</body>');
if (start < 0 || end < 0) throw new Error('index.html is missing the development entry block');
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
const banner = '<!-- Cross-Sections ' + pkg.version + ', portable edition. Generated by tools/build.js from src/; do not edit by hand. Source: https://github.com/ChaseHendrick/cross-section (MIT). Includes three.js (MIT) and cannon-es (MIT); their notices follow the bundle. -->\n';
html = html.slice(0, start) +
  '<script>window.XS_THUMBS = ' + JSON.stringify(thumbs) + ';</script>\n' +
  '<script type="module">\n' + js + '</script>\n' + html.slice(end);
html = html.replace('<!doctype html>', '<!doctype html>\n' + banner);

if (check) {
  const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (cur !== html) {
    console.error('dist/cross-sections.html is out of date. Run: node tools/build.js');
    process.exit(1);
  }
  console.log('dist/cross-sections.html is up to date (' + (html.length / 1e6).toFixed(2) + ' MB).');
} else {
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, html);
  console.log('Wrote dist/cross-sections.html (' + (html.length / 1e6).toFixed(2) + ' MB, ' + Object.keys(thumbs).length + ' thumbnails).');
}
